### PR TITLE
Updated references from docs.microsoft.com - to learn

### PR DESCRIPTION
**Pull request by ElYusubov**
# Overview/Summary

The PR is updating references in documentation from docs.microsoft.com - to learn.microsoft.

## This PR fixes/adds/changes/removes

1. Updates the reference links in the documentation and minor document formatting.

### Breaking Changes

1. No breaking changes were introduced.

## Testing Evidence

Replace this with any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://github.com/Azure/bicep-lz-vending/wiki/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/bicep-lz-vending/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/bicep-lz-vending/issues)
- [ ] *(LZ-Vending Core Team Only)* Associated it with relevant [ADO Items](https://aka.ms/lz-vending/backlog)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/bicep-lz-vending/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated one or more of the following tests *(if required)*
  - [Unit](https://github.com/Azure/bicep-lz-vending/blob/main/.github/workflows/bicep-build-to-validate.yml)
  - [Linting](https://github.com/Azure/bicep-lz-vending/tree/main/.github/workflows/code-review.yml)
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Module READMEs, Wiki Docs etc.)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Thanks @ElYusubov for the PR. 

Please roll back all the changes to the files in the CARML directory. As we just pull in this directly from the CARML repo. 

So please make the changes to these files in the upstream CARML repo - https://aka.ms/CARML 

Thanks

Jack

**Comment by ElYusubov** [comment]
Thanks for insights @jtracey93!
I will push this update to the CARML later tonight :)

**Comment by ElYusubov** [comment]
Rolling back the updates.

**Comment by ElYusubov** [comment]
Rolling back the updates.

**Pull request closed without merging**
